EnForFun - Copy/EnForFun.2020.03.31/EnForFun/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
from django.urls import path

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]


urlpatterns += [
    path('languageTests/', include('languageTests.urls')),
]


from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('l', RedirectView.as_view(url='/languageTests/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

EnForFun - Copy/EnForFun.2020.03.31/catalog/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Feb  1 01:10:36 2019

@author: A
"""

from django.urls import path
from . import views

urlpatterns = [
     path('', views.index, name='index'),
     path('books/', views.BookListView.as_view(), name='books'),
     path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
     path('authors/', views.AuthorListView.as_view(), name='authors'),
     path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [   
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

urlpatterns += [   
    path('borrowedbooks/', views.AllBorrowedBooks.as_view(), name='all-borrowed'),
]

urlpatterns += [   
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

urlpatterns += [  
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

urlpatterns += [  
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
]

EnForFun - Copy/EnForFun.2020.03.31/languageTests/urls.py
# -*- coding: utf-8 -*-
"""
Created on Wed Feb  6 19:05:30 2019

@author: A
"""


from django.urls import path, re_path
from . import views

urlpatterns = [
     path('', views.index, name='index_lt'),
     path('topics/', views.TopicListView.as_view(), name='topics'),
     path('topics/<int:pk>', views.topic_view, name='topic'),
     #path('topics/', views.index, name='topics'),
     path('tutorials/', views.TutorialsListView.as_view(), name='tutorials'),
     path('languagetest/<int:pk>', views.LanguageTestDetailView.as_view(), name='languagetest_detail'),
]

urlpatterns += [
        path('languagetest/<int:pk>/take_a_test', views.pass_a_test, name='take_a_test'),
        path('tutorials/<int:pk>', views.tutorial_view, name='tutorial'),
]

EnForFun - Copy/EnForFun.2020.03.31/languageTests/models.py
from django.db import models
import uuid # Required for unique excersises 
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
# Create your models here.


class Explanation(models.Model):
    """Model representing explanation for wrong answers"""
    answer       = models.ForeignKey('Answer',on_delete=models.CASCADE, null=True, help_text='Explanation of the answer')
    language     = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    explain_text = models.TextField(max_length=1000, default="", help_text='Explanation text for the answer')
    wrong_answer = models.CharField(max_length=200, null=True, help_text='Expected wrong answer')

class Answer(models.Model):
    """Model representing answer for excersise"""
    excersise = models.ForeignKey('Excersise',on_delete=models.CASCADE, null=True, help_text='Answer of excersise')
    explanation_string = models.TextField(max_length=1000, null=True,help_text="Enter the explanation")
    answer_string = models.CharField(max_length=100,help_text="Enter the answer")
    possible_answers = models.CharField(max_length=100, null=True, help_text="Enter the possible answers")

class Language(models.Model):
    """Model respresenting language""" 
    name = models.CharField(max_length=100,help_text="Enter the language (e.g. English, French, Japanese etc.)")
    
    class Meta:
        ordering = ['name']
    
    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

class TutorialComponent(models.Model):
    TYPES = (
        ('e','Explanation'),
        ('p','Picture'),
        ('c','Chart'),
        ('x','Example')
    ) 
    
    component_type = models.CharField(
        max_length=1,
        choices=TYPES,
        blank=True,
        default='e',
        help_text='Component type',
    )
    
    component_text = models.TextField(max_length=10000, default="", blank=True, help_text='Explanation text')
    
    tutorial = models.ForeignKey('Tutorial',on_delete=models.CASCADE, null=True, blank=True, help_text='Tutorial')
    

    
class Tutorial(models.Model):
    LEVELS = (
        ('b', 'Beginner'),
        ('i', 'Intermediate'),
        ('e', 'Expert'),
    )
    tutorial_title = models.CharField(max_length=200, help_text='Enter a Tutorial Name (e.g. Present simple #1)')
    level = models.CharField(
        max_length=1,
        choices=LEVELS,
        blank=True,
        default='b',
        help_text='Tutorial level',
    )
                                                                                        
    def __str__(self):
        """String for representing the Model object."""
        return f'' + self.tutorial_title
    
    def return_level_str(self):
        dict_levels=dict(self.LEVELS)
        return dict_levels[self.level]
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        #return reverse('languagetest_detail', args=[str(self.id)]) 
        return reverse('tutorial', args=[str(self.id)]) 
    
    
class Excersise(models.Model):
    LEVELS = (
        ('b', 'Beginner'),
        ('i', 'Intermediate'),
        ('e', 'Expert'),
    )

    TYPES = (
        ('w','Choose the word'),
        ('s','Construct a sentance'),
        ('t','Type the word')
    )  
    
    #level = models.CharField(
    #    max_length=1,
    #    choices=LEVELS,
    #    blank=True,
    #    default='b',
    #    help_text='Excersise level',
    #)

    exercise_type = models.CharField(
        max_length=1,
        choices=TYPES,
        blank=True,
        default='w',
        help_text='Tests type',
    )
    
    id   = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular excersise')
    text = models.TextField(max_length=1000, default="", null=True, help_text='Text of the excersise')
    
    
    language_test = models.ForeignKey('LanguageTest',on_delete=models.CASCADE, null=True, help_text='Unique test')
    #language_test_group = models.ForeignKey('LanguageTestGroup',on_delete=models.SET_NULL, null=True, help_text='Unique test')
    chars_to_display = 80
    
    def __str__(self):
        """String for representing the Model object."""
        #return f'Ex#:{self.id}' + self.display_text()
        return f'Ex:' + self.display_text()
    
    def display_text(self):
        output_text=self.text
        if len(self.text) > self.chars_to_display:
            output_text=output_text[:self.chars_to_display] + "..."
        return output_text
    
    def display_language_test(self):
        return self.language_test.title
    
class Topic(models.Model):
    LEVELS = (
        ('b', 'Beginner'),
        ('i', 'Intermediate'),
        ('e', 'Expert'),
    )

    level = models.CharField(
        max_length=1,
        choices=LEVELS,
        blank=True,
        default='b',
        help_text='Tests level',
    )   
    
    #language_test = models.ForeignKey('LanguageTest',on_delete=models.SET_NULL, null=True, blank=True, help_text='Unique test')
    title = models.CharField(max_length=200, help_text='Enter a Test Name (e.g. Test #1)')
    
    def return_level_str(self):
        dict_levels=dict(self.LEVELS)
        return dict_levels[self.level]    
    
    def __str__(self):
        """String for representing the Model object."""
        return str(self.title)
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        #return reverse('languagetest_detail', args=[str(self.id)]) 
        return reverse('topic', args=[str(self.id)]) 
    
class LanguageTest(models.Model):
    """Model representing a Language Test."""
    
    #answers = models.CharField(default="", max_length=1024)
    task   = models.CharField(default="", null=True, max_length=1024)
    number =  models.IntegerField(null=True,unique=True)
    #LEVELS = (
    #    ('b', 'Beginner'),
    #    ('i', 'Intermediate'),
    #    ('e', 'Expert'),
    #)

    #level = models.CharField(
    #    max_length=1,
    #    choices=LEVELS,
    #    blank=True,
    #    default='b',
    #    help_text='Tests level',
    #)                                                           
                                                                           
    def __str__(self):
        """String for representing the Model object."""
        return str(self.number)

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        #return reverse('languagetest_detail', args=[str(self.id)]) 
        return reverse('take_a_test', args=[str(self.id)]) 
       
    
    #def return_level_str(self):
    #    dict_levels=dict(self.LEVELS)
    #    return dict_levels[self.level]
    topic = models.ForeignKey('Topic',on_delete=models.CASCADE, null=True, help_text='Unique test')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    #native_language = models.ForeignKey('Language', on_delete=models.SET_NULL)
    #excersise       = models.ManyToManyField(Excersise, help_text='Select excersises for current Test')  

EnForFun - Copy/EnForFun.2020.03.31/languageTests/forms.py
import datetime 

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class TakeATestDummy(forms.Form):
        
    testDict={}
    def set_tests_dict(self,dict_to_set):
        self.testDict=dict_to_set
    
    def append_new_test(self,name,count):
        self.testDict[name]=count
        pass
    def get_tests_dict(self):
        return self.testDict
 
class TakeATestFormer(forms.Form):
    
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        
    def get_language_tests(self):
        pass

    
    
    #renewal_date = forms.DateField(help_text=language_test)
    #for excersice in language_test.excersise_set:
    #       pass      
    
    #def clean_renewal_date(self):
    #    data = self.cleaned_data['renewal_date']
        
        # Check if a date is not  in the past. 
        #if data < datetime.date.today():
        #    raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        #if data > datetime.date.today() + datetime.timedelta(weeks=4):
        #    raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
    #    return data  

EnForFun - Copy/EnForFun.2020.03.31/languageTests/templates/languageTests/Topic_list.html
{% extends "base_generic2.html" %}

{% block content %}


  <div class="tests-header"><h1>Topics</h1><div>
  <div>
  
  Select Level 
  
  </div>   
  
  <select class="selectstrove" id="select_level">
      <option value="All">All</option>
      {% for level in levels %}
         <option value="{{ level.0 }}" {% if request.GET.level == level.0 %} selected {% endif %} >{{ level.1 }}</option>
      {% endfor%}                  
  </select>   

  {% if Topic_list %}  
  
  <div class="container">
    {% for topic in Topic_list %}
       
      {% if forloop.first %}<div class="row">{% endif %}  
          <div class="col col-xs-4 language-tests margin">
              <a href="{{ topic.get_absolute_url }}">         
                  <div class="button-hover">
                      <div class="test-title">{{ topic.title}}</div>
                      <div class="test-level">({{ topic.return_level_str }})</div>
                  </div>
              </a>
          </div>
      {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}    
      {% if forloop.last %}</div>{% endif %}    
    {% endfor %}
  {% else %}
      <p>There are no tests.</p>
  {% endif %}  
    
  </div id="end">

    {% block javascript %}
      <script>
        $("#select_level").change(function () {
          var level= $(this).val()
          console.log( $(this).val() );
          window.open('{% url "topics" %}?level=' + level,'_self',false)
        });
      </script>
    {% endblock %}

     
{% endblock %}

EnForFun - Copy/EnForFun.2020.03.31/languageTests/templates/languageTests/dragndrop_widget.html
<input type="hidden" id="widget-{{ widget.name }}" class="dragndrop-widget" name="{{ widget.name }}" 
{% if widget.value %} 
value="{{ widget.value }}" 
{% else %} 
value=" " 
{% endif %}/>

EnForFun - Copy/EnForFun.2020.03.31/languageTests/templates/languageTests/languagetest_detail.html
{% extends "base_generic2.html" %}

{% block content %}
  <h1 class="test-header">Title: {{ languagetest.title }}</h1>
   
  <!--<p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  -->

  <div style="margin-left:20px;margin-top:20px">
    <h4>Exs</h4>
    {% if languagetest.excersise_set.all %}
        {% for excersise in languagetest.excersise_set.all %}
          <hr>
          <p>{{ excersise.text }}</p> 
        {% endfor %}
    {% else %}
          <p>There is no excersise for this test</p>  
    {% endif %}    
  </div>
{% endblock %}

EnForFun - Copy/EnForFun.2020.03.31/languageTests/templates/languageTests/success.html
{% extends "base_generic2.html" %}
{% load custom_tags %}


{% block content %}
  <h1>Title: {{ language_test.title }}</h1>  
  <h1>PASSED !!!</h1> 

{% endblock %}

EnForFun - Copy/EnForFun.2020.03.31/languageTests/templates/languageTests/take_a_test.html
{% extends "base_generic2.html" %}
{% load custom_tags %}


{% block content %}
  <h1 class="test-header">{{ language_test.task }}</h1>  
  <form action="" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    
    {% if form.non_field_errors %}
        <ul>
          {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
    {% endif %}
    
  
    <div class="form-group">
    
    {% if language_test.excersise_set.all %}
        
        {% for excersise in language_test.excersise_set.all %}
          <div class="ex-wrapper{{forloop.counter}} ex-wrapper">
          {% if excersise.exercise_type == "w" %}
              <p>{% excersise_choose_the_word excersise.text form form.get_tests_dict|get_item:excersise.id %}</p>           
          {% elif excersise.exercise_type == "s" %}
              <p>{% excersise_construct_a_sentence excersise.text form form.get_tests_dict|get_item:excersise.id excersise.id%}</p>
          {% elif excersise.exercise_type == "t" %}
              <p>{% excersise_type_the_word excersise.text form form.get_tests_dict|get_item:excersise.id %}</p>
          {% else %}
              <p>I don't have an idea what excercise this is </p>        
          {% endif %}
          <p>
          <!--p>{# excersise.text #}</p-->
          <!--p>{{ output2 }}</p-->
          </div> 
        {% endfor %}
        </div">
    {% else %}
          <p>There is no excersise for this test</p>  
    {% endif %}
    
    <div class="wrapperbtn">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>   
  </form>

{% endblock %}

EnForFun - Copy/EnForFun.2020.03.31/languageTests/templates/languageTests/take_a_test_bank.html
{% extends "base_generic2.html" %}
{% load custom_tags %}


{% block content %}
  <h1>Title: {{ language_test.title }}</h1>  
   
    

  <form action="" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    
    {% if form.non_field_errors %}
        <ul>
          {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
    {% endif %}
    
    
    {% for hidden_field in form.hidden_fields %}
        {% if hidden_field.errors %}
          <ul>
            {% for error in hidden_field.errors %}
              <li>(Hidden field {{ hidden_field.name }}) {{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
        {{ hidden_field }}
    {% endfor %}
    
    <table border=1>
    <div class="form-group">
    
    {% if language_test.excersise_set.all %}
        {% for excersise in language_test.excersise_set.all %}
          <hr>
          <p>{% add_choices_to_excersise excersise.text form form.get_tests_dict|get_item:excersise.id %}</p>
          <p>{# excersise.text #}</p>
          <br/> 
          <!--p>{{ output2 }}</p--> 
        {% endfor %}
    {% else %}
          <p>There is no excersise for this test</p>  
    {% endif %}
    
    
    
    
    {% comment %}
    {% for field in form.visible_fields %}
      <tr>
        <th>{{ field.label_tag }}</th>
        <td>
          {% if field.errors %}
            <ul>
              {% for error in field.errors %}
                <li>{{ error }}</li>
              {% endfor %}
            </ul>
          {% endif %}
          {{ field }}
          
  
          {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}
        </td>
      </tr>  
    </div>  
    {% endfor %}
    {% endcomment %}
    </table>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

EnForFun - Copy/EnForFun.2020.03.31/languageTests/templates/languageTests/topic.html
{% extends "base_generic2.html" %}

{% block content %}


  <div class="tests-header"><h1>{{ topic.title }}</h1><div>

  


  {% if topic %}  
  
  <div class="container">
    {% for language_test in language_tests %}
       
      {% if forloop.first %}<div class="row">{% endif %}  
          <div class="col col-xs-2 language-tests margin">
              <a href="{{ language_test.get_absolute_url }}">         
                  <div class="button-hover">
                      <div class="test-title">{{ language_test.number}}</div>
                  </div>
              </a>
          </div>
      {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}    
      {% if forloop.last %}</div>{% endif %}    
    {% endfor %}
  {% else %}
      <p>There are no tests.</p>
  {% endif %}  
    
  </div id="end">



     
{% endblock %}

EnForFun - Copy/EnForFun.2020.03.31/languageTests/templates/languageTests/tutorial.html
{% extends "base_generic2.html" %}
{% load custom_tags %}


{% block content %}
  <h1 class="test-header">{{ tutorial.tutorial_title }}</h1>  

    
  
    <div class="Explanation-wrapper">
    {% if tutorial.tutorialcomponent_set.all %}
        
        {% for tutorial_comp in tutorial.tutorialcomponent_set.all %}
          <div class="a">
            {{ tutorial_comp.component_text }}
          <p>
          </div> 
        {% endfor %}
    </div">
    {% else %}
          <p>There is no excersise for this test</p>  
    {% endif %}
       

{% endblock %}